#commands to initialize each env separately 

# For development environment
terraform init -backend-config="environments/dev/backend.hcl"

# For staging environment  
terraform init -backend-config="environments/staging/backend.hcl"

# For production environment
terraform init -backend-config="environments/prod/backend.hcl"